// create
export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';

// read
export const FETCH_LISTS_FOR_USER = 'FETCH_LISTS_FOR_USER';
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_FOR_USER_SUCCESS';

export const OBSERVE_LIST = 'OBSERVE_LIST';
export const STOP_OBSERVING_LIST = 'STOP_OBSERVING_LIST';
export const ON_LIST_UPDATE = 'ON_LIST_UPDATE';

// update
export const UPDATE_LIST_ITEMS = 'UPDATE_LIST';
export const PUBLISH_LIST = 'PUBLISH_LIST';
export const UNPUBLISH_LIST = 'UNPUBLISH_LIST';
export const SHARE_LIST = 'SHARE_LIST';
export const ASSIGN_LIST_OWNERSHIP = 'ASSIGN_OWNERSHIP';
export const REMOVE_USER_FROM_LIST = 'REMOVE_USER_FROM_LIST';
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS';

// delete
export const DELETE_LIST = 'DELETE_LIST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';

// misc
export const EDIT_ACTIVE_LIST = 'EDIT_ACTIVE_LIST';
export const SET_EDIT_UPDATE_MODE = 'SET_EDIT_UPDATE_MODE';
export const SET_LIVE_UPDATE_MODE = 'SET_LIVE_UPDATE_MODE';
