// create
export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';

// read
export const SET_ACTIVE_LIST_ID = 'SET_ACTIVE_LIST_ID';
export const USER_LISTS_UPDATED = 'USER_LISTS_UPDATED';
export const OBSERVE_LISTS_FOR_USER = 'OBSERVE_LISTS_FOR_USER';
export const STOP_OBSERVING_LISTS_FOR_USER = 'STOP_OBSERVING_LISTS_FOR_USER';

export const OBSERVE_LIST = 'OBSERVE_LIST';
export const STOP_OBSERVING_LIST = 'STOP_OBSERVING_LIST';
export const ON_LIST_UPDATE = 'ON_LIST_UPDATE';

// update
export const CREATE_LIST_ITEM = 'CREATE_LIST_ITEM';
export const UPDATE_LIST_ITEM = 'UPDATE_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const SELECT_LIST_ITEM = 'SELECT_LIST_ITEM';
export const SET_LIST_TITLE = 'SET_LIST_TITLE';
export const PUBLISH_LIST = 'PUBLISH_LIST';
export const UNPUBLISH_LIST = 'UNPUBLISH_LIST';
export const SHARE_LIST = 'SHARE_LIST';
export const ASSIGN_LIST_OWNERSHIP = 'ASSIGN_OWNERSHIP';
export const REMOVE_USER_FROM_LIST = 'REMOVE_USER_FROM_LIST';
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS';

// delete
export const DELETE_LIST = 'DELETE_LIST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';

// misc
export const EDIT_ACTIVE_LIST = 'EDIT_ACTIVE_LIST';
export const SET_EDIT_UPDATE_MODE = 'SET_EDIT_UPDATE_MODE';
export const SET_LIVE_UPDATE_MODE = 'SET_LIVE_UPDATE_MODE';
export const CLEAR_LISTS = 'CLEAR_LISTS';
