export const NETWORK_OPERATION_START = 'NETWORK_OPERATION_START';
export const NETWORK_OPERATION_SUCCESS = 'NETWORK_OPERATION_SUCCESS';
export const NETWORK_OPERATION_FAIL = 'NETWORK_OPERATION_FAIL';
